export { default as getClassName } from './getClassName'
export { default as isFunction } from './isFunction'
export { default as isNumber } from './isNumber'
export { default as isObject } from './isObject'
export { default as isString } from './isString'
